#!/bin/bash

#$ -M zpan3@nd.edu   # Email address for job notification
#$ -m abe            # Send mail when job begins, ends and aborts
#$ -q gpu@@yshi4_lab           # Specify queue
#$ -l gpu_card=1
#$ -pe smp 8
#$ -N  mae_monuseg_3img     # Specify job name

conda activate ddpm_a10
export OMP_NUM_THREADS=1

DATASET="monuseg_1" # Available datasets: bedroom_28, ffhq_34, cat_15, horse_21, celeba_19, ade_bedroom_30
python train_interpreter.py --exp ./experiments/${DATASET}/mae.json
